#include "bf3/patch/resource_builder.hpp"
#include "bf3/hash.hpp"
#include "bf3/patch/cas_blocks.hpp"
#include <fstream>
#include <iomanip>
#include <sstream>

namespace bf3::patch {
BuiltResource rebuild_resource(const ResourceSpec& spec, const Bytes& original) {
    if (original.size() != spec.stored_size || sha256(original) != spec.original_sha256) {
        throw std::runtime_error(std::string("Original resource identity mismatch: ") +
                                 spec.resource);
    }
    BuiltResource result{original, {}};
    if (spec.decoded_size) {
        auto movie = patch_prompt_widgets(unpack_cas(original, spec.decoded_size));
        result.bytes = pack_cas_fixed(movie.bytes, spec.stored_size);
        result.prompt_edits = std::move(movie.edits);
    } else {
        // Preflight every edit before changing any bytes, including signed IDs.
        for (std::size_t i = 0; i < spec.edit_count; ++i) {
            const auto& edit = spec.edits[i];
            if (read_u32(original, edit.offset) != static_cast<std::uint32_t>(edit.before)) {
                throw std::runtime_error(std::string("EBX field guard failed: ") + edit.field);
            }
            for (std::size_t j = 0; j < i; ++j) {
                const auto previous = spec.edits[j].offset;
                if (edit.offset < previous + 4 && previous < edit.offset + 4) {
                    throw std::runtime_error("Overlapping EBX edits");
                }
            }
        }
        for (std::size_t i = 0; i < spec.edit_count; ++i) {
            const auto& edit = spec.edits[i];
            const auto value = static_cast<std::uint32_t>(edit.after);
            for (unsigned byte = 0; byte < 4; ++byte) {
                result.bytes[edit.offset + byte] = static_cast<std::uint8_t>(value >> (8 * byte));
            }
        }
    }
    if (result.bytes.size() != spec.stored_size || sha256(result.bytes) != spec.patched_sha256 ||
        sha1(result.bytes) != spec.patched_sha1) {
        throw std::runtime_error(std::string("Rebuilt payload differs from pinned 0.22.2: ") +
                                 spec.resource);
    }
    return result;
}

Bytes read_resource(const std::filesystem::path& path, std::uint64_t offset, std::size_t size) {
    const auto file_size = std::filesystem::file_size(path);
    if (offset > file_size || size > file_size - offset)
        throw std::runtime_error("Resource outside file bounds");
    std::ifstream file(path, std::ios::binary);
    if (!file)
        throw std::runtime_error("Cannot open resource file: " + path.string());
    file.seekg(static_cast<std::streamoff>(offset));
    Bytes bytes(size);
    if (!file.read(reinterpret_cast<char*>(bytes.data()), static_cast<std::streamsize>(size))) {
        throw std::runtime_error("Resource read failed: " + path.string());
    }
    return bytes;
}

void write_bytes(const std::filesystem::path& path, const Bytes& bytes) {
    std::ofstream file(path, std::ios::binary | std::ios::trunc);
    if (!file || !file.write(reinterpret_cast<const char*>(bytes.data()),
                             static_cast<std::streamsize>(bytes.size()))) {
        throw std::runtime_error("Cannot write output: " + path.string());
    }
    file.close();
    if (!file)
        throw std::runtime_error("Cannot flush output: " + path.string());
}

namespace {
std::string json_string(const char* value) {
    std::ostringstream text;
    text << '"';
    for (auto p = value; *p; ++p) {
        const auto c = static_cast<unsigned char>(*p);
        if (c == '"' || c == '\\')
            text << '\\' << char(c);
        else if (c < 32)
            text << "\\u00" << std::hex << std::setw(2) << std::setfill('0') << unsigned(c)
                 << std::dec;
        else
            text << char(c);
    }
    text << '"';
    return text.str();
}

void hash_array(std::ostream& output, const char* digest) {
    output << '{';
    auto bytes = unhex(digest);
    if (bytes.size() != 20)
        throw std::runtime_error("Invalid release SHA1");
    for (std::size_t i = 0; i < bytes.size(); ++i) {
        if (i)
            output << ',';
        output << "0x" << std::hex << std::setw(2) << std::setfill('0') << unsigned(bytes[i]);
    }
    output << std::dec << '}';
}
} // namespace

std::string generate_hash_rules() {
    std::ostringstream output;
    output << "// Generated by bf3-resource-builder from the pinned C++ release specification.\n";
    output << "const HashRule hash_rule_data[] = {\n";
    for (std::size_t i = 0; i < release_resource_count(); ++i) {
        const auto& spec = release_resources()[i];
        output << "    {";
        hash_array(output, spec.patched_sha1);
        output << ", ";
        hash_array(output, spec.catalog_sha1);
        output << ", " << json_string(spec.kind) << "},\n";
    }
    output << "};\n";
    return output.str();
}

std::string generate_manifest() {
    std::ostringstream output;
    output << "{\n  \"version\": " << json_string(release_version)
           << ",\n  \"runtimeVerified\": false,\n  \"generator\": \"C++\",\n  \"assets\": [\n";
    for (std::size_t i = 0; i < release_resource_count(); ++i) {
        const auto& spec = release_resources()[i];
        if (i)
            output << ",\n";
        output << "    {\"kind\": " << json_string(spec.kind)
               << ", \"resource\": " << json_string(spec.resource)
               << ", \"path\": " << json_string(spec.archive) << ", \"offset\": " << spec.offset
               << ", \"size\": " << spec.stored_size
               << ", \"originalFile\": " << json_string(spec.original_file)
               << ", \"patchedFile\": " << json_string(spec.patched_file)
               << ", \"originalSha256\": " << json_string(spec.original_sha256)
               << ", \"patchedSha256\": " << json_string(spec.patched_sha256)
               << ", \"catalogIdentifier\": " << json_string(spec.catalog_sha1)
               << ", \"patchedSha1\": " << json_string(spec.patched_sha1) << '}';
    }
    output << "\n  ],\n  \"files\": [\n";
    for (std::size_t i = 0; i < release_archive_count(); ++i) {
        const auto& spec = release_archives()[i];
        if (i)
            output << ",\n";
        output << "    {\"path\": " << json_string(spec.path) << ", \"size\": " << spec.size
               << ", \"originalSha256\": " << json_string(spec.original_sha256)
               << ", \"patchedSha256\": " << json_string(spec.patched_sha256) << '}';
    }
    output << "\n  ],\n  \"metadata\": [\n";
    for (std::size_t i = 0; i < release_metadata_count(); ++i) {
        const auto& spec = release_metadata()[i];
        if (i)
            output << ",\n";
        output << "    {\"path\": " << json_string(spec.path)
               << ", \"sha256\": " << json_string(spec.sha256) << '}';
    }
    output << "\n  ]\n}\n";
    return output.str();
}

void verify_original_game(const std::filesystem::path& game) {
    for (std::size_t i = 0; i < release_archive_count(); ++i) {
        const auto& spec = release_archives()[i];
        const auto path = game / spec.path;
        if (std::filesystem::file_size(path) != spec.size ||
            file_sha256(path) != spec.original_sha256) {
            throw std::runtime_error(
                std::string("Expected an unmodified supported game archive: ") + spec.path);
        }
    }
    for (std::size_t i = 0; i < release_metadata_count(); ++i) {
        const auto& spec = release_metadata()[i];
        if (file_sha256(game / spec.path) != spec.sha256) {
            throw std::runtime_error(std::string("Signed game metadata mismatch: ") + spec.path);
        }
    }
}
} // namespace bf3::patch
